# Generated by Django 6.0.7 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR Administrator'), ('hr_limited', 'HR (Limited)'), ('employee', 'Employee'), ('intern', 'Intern')], default='employee', max_length=20),
        ),
    ]
