# Generated by Django 6.0.7 on 2026-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR Administrator'), ('hr_executive', 'HR Executive'), ('employee', 'Employee'), ('intern', 'Intern')], default='employee', max_length=20),
        ),
    ]
