# Generated by Django 6.0.7 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='call_status',
            field=models.CharField(choices=[('called', 'Called'), ('not_called', 'Not Called')], default='not_called', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='last_called_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.CharField(choices=[('updated', 'Updated'), ('not_updated', 'Not Updated')], default='not_updated', max_length=20),
        ),
    ]
