# Generated by Django 6.0.6 on 2026-07-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('position_applied', models.CharField(max_length=200)),
                ('college_name', models.CharField(blank=True, help_text='College/University the candidate studied at', max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('interview_scheduled_date', models.DateField(blank=True, null=True)),
                ('interview_scheduled_time', models.TimeField(blank=True, null=True)),
                ('interview_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('interview_notes', models.TextField(blank=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_rating', models.IntegerField(blank=True, help_text='Rating out of 10', null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('joined', 'Joined'), ('rejected_offer', 'Rejected Offer')], default='applied', max_length=20)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('offer_letter_generated', models.BooleanField(default=False)),
                ('offer_letter_file', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('offer_letter_sent', models.BooleanField(default=False)),
                ('offer_letter_sent_date', models.DateTimeField(blank=True, null=True)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('welcome_email_sent_date', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('resent', 'Resent')], default='pending', max_length=20)),
                ('email_attempts', models.IntegerField(default=0)),
                ('email_error_message', models.TextField(blank=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('joining_confirmed', models.BooleanField(default=False)),
                ('joining_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewed_candidates', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('location', models.CharField(blank=True, default='Kollam, Kerala', max_length=150)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='employees.department')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
