# Generated by Django 6.0.7 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='internship_type',
            field=models.CharField(choices=[('unpaid', 'Non-Paid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='intern',
            name='stipend_amount',
            field=models.IntegerField(blank=True, choices=[(3000, '₹3,000 / month'), (5000, '₹5,000 / month')], null=True),
        ),
    ]
