# Generated by Django 6.0.7 on 2026-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_intern_internship_type_intern_stipend_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date the intern paid the internship fee', null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='stipend_amount',
            field=models.IntegerField(blank=True, choices=[(3000, '₹3,000'), (5000, '₹5,000')], null=True),
        ),
    ]
