# Generated by Django 5.2.3 on 2026-07-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfromhome',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='workfromhome',
            name='to_date',
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='expected_hours',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='internships.intern'),
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workfromhome',
            name='working_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workfromhome',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='employees.employee'),
        ),
    ]
