# Generated by Django 6.0.7 on 2026-08-11 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='leaves_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='lop_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
